name: image_filter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.9.2
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  before_after: ^3.2.0
  ffi: ^2.1.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true
